"""initial migration

Revision ID: 52df7ae18f0b
Revises: 
Create Date: 2022-11-03 15:47:09.983724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52df7ae18f0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('module_code', sa.String(length=10), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=125), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_module_code'), 'assessments', ['module_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessments_module_code'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
